# Loadbalancer service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

# This will only work over cloud providers like AWS, GCP, Azure
# In local we can use NodePort